version: '3'

services:
  rabbitmq:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: websocket-chat-queue
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613